version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DJANGO_DB_HOST=db #services:db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplepw
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:./backend
    command: python manage.py runserver 0:8000
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:./frontend
    ports:
      - "4000:3000"
    command: ["npm", "start"]